pastebin/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^getpaste/([\da-zA-Z]+)$', views.getpaste, name='getpaste'),
    url(r'^paste$', views.paste, name='paste'),
    url(r'^([\da-zA-Z]+)$', views.detail, name='detail'),
    url(r'^$', views.index, name='index'),
    url(r'^([\da-zA-Z]+)/createcomment$', views.createcomment, name='createcomment')
]

pastebin/models.py
from django.db import models

class Paste(models.Model):
    title = models.CharField(max_length=200)
    public = models.BooleanField()
    text = models.TextField()
    pub_date = models.DateTimeField('date published')
    key = models.CharField(max_length=15)
    syntax = models.CharField(max_length=15)

class Comment(models.Model):
    title = models.CharField(max_length=200)
    text = models.CharField(max_length=2000)
    pub_date = models.DateTimeField('date published')
    paste = models.ForeignKey(Paste)

pastebin/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from random import randint
from collections import ChainMap

from tempfile import TemporaryFile
from .language import language
from .models import Paste, Comment

def index(request):
    latest_paste_list = Paste.objects.order_by('-pub_date').filter(public=True)[:10]
    context = {'latest_paste_list': latest_paste_list, 'language': language}
    return render(request, 'pastebin/index.html', context)

def detail(request, paste_id):
    paste = get_object_or_404(Paste, key=paste_id)
    return render(request, 'pastebin/detail.html', {'paste':paste})

def paste(request):
    text = request.POST['text']
    title = request.POST['title']
    syntax = request.POST['syntax']
    if title is "":
        title = "Untitled";
    if "public" in request.POST:
    	public = True
    else:
        public = False
    key = ''
    for i in range(0,10):
        char = randint(48, 122)
        while char > 90 and char < 97 or char > 57 and char < 65:
            char = randint(48, 122)
        key += chr(char)
    languages = ChainMap(*language);

    paste = Paste(title=title, text=text, public=public, pub_date=timezone.now(), key=key, syntax=languages[syntax])
    paste.save()
    return redirect("/%s" % key)

def getpaste(request, paste_id):
    a = get_object_or_404(Paste, key=paste_id).text
    response= HttpResponse(a, content_type='text/plain')
    response['Content-Disposition'] = 'attachment; filename="%s.txt"' % paste_id
    return response;

def createcomment(request, key):
    text = request.POST['text']
    title = request.POST['title']
    if title is "":
      title = "None";
    paste = get_object_or_404(Paste, key=key)
    comment = Comment(title=title, text=text, pub_date=timezone.now(), paste=paste)
    comment.save()
    return redirect("/%s" % key)

pastebin/templates/pastebin/base.html
{% load static %}

<html>
<link rel="stylesheet" href="{% static 'pastebin/styles.css' %}">
  {% block header %}
  {% endblock %}
<head>
</head>
<body>
<div id="header">
  <div id="header-inner">
    <h1 id="title"><a href="/">PasteBin</a></h1>
  </div>
</div>
<div id="body">
  {% block content %}
  {% endblock %}
</div>
</body>
</html>

pastebin/templates/pastebin/detail.html
{% extends 'pastebin/base.html' %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'pastebin/detail.css' %}">
<link rel="stylesheet" href="{% static 'pastebin/prism.css' %}">
<script src="{% static 'pastebin/prism.js' %}"></script>
{% endblock %}
{% block content %}
<div id="paste-header">
<form id="paste-download" action="getpaste/{{paste.key}}" method="get">
<input type="submit" value="Download Paste"></form>
<div id="paste-name">Title: {{ paste.title }}</div>
<div id="paste-date">{{ paste.pub_date }}</div>
</div>
<div id="paste-text">
<pre><code class="language-{{ paste.syntax }}">{{ paste.text }}</code></pre>
</div>
<form class="commentForm" action="{{paste.key}}/createcomment" method="Post">
    {% csrf_token %}
    <input type="text" name="title" placeholder="Name">
    <textarea name="text" placeholder="Comment"></textarea>
    <input type="submit" value="Submit Comment">
</form>
<div class="comments">
{% for comment in paste.comment_set.all %}
<div class="comment">
<div class="title" title="{{comment.pub_date}}">{{ comment.title }} Says:</div>
<div class="text">{{ comment.text }}</div>
</div>
{% endfor %}
</div>
{% endblock %}

pastebin/templates/pastebin/index.html
{% extends 'pastebin/base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'pastebin/index.css' %}">
{% endblock %}
{% block content %}

  <form action="paste" method="Post">
  <h3>New Paste</h3>
    {% csrf_token %}
    <textarea name="text" placeholder="Text"></textarea>
    <input type="text" name="title" placeholder="Title (optional)"><br />
    <label>Syntax Highlighting: <select name="syntax">
      {% for lang in language %}
        {% for key in lang %}
          <option value="{{key}}">{{key}}</option>
        {% endfor %}
      {% endfor %}
    </select></label><br />
    <label><input type="checkbox" name="public" checked="true">List publicly</label><br />
    <input type="submit" value="Create Paste">
  </form>

<div id="mostrecent">
<h3>Most Recent Pastes</h3>

{% if latest_paste_list %}
    <ul>
    {% for paste in latest_paste_list %}
        <li><a href="/{{ paste.key }}">{{ paste.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No pastes are available.</p>
{% endif %}
</div>

{% endblock %}